export default {
  colors: {
    background: '#fff',
    buttonPrimaryFill: '#1d1f1f',
    buttonPrimaryText: '#fff',
    buttonPrimarySpinnerFill: '#fff',
    buttonBorderedText: '#1d1f1f',
    buttonBorderedBorder: '#1d1f1f',
    buttonBorderedSpinnerFill: '#1d1f1f',
    buttonMinimalText: '#1d1f1f',
    buttonMinimalSpinnerFill: '1d1f1f',
    headerNavigationFill: '#000',
    listSectionHeaderFill: '#fff',
    snackbarFill: '#1d1f1f',
    snackbarText: '#fff',
    iconFill: '#1d1f1f',
    contentPrimary: '#000',
    contentSecondary: '#545454',
    contentTertiary: '#757575',
    contentPositive: '#47fb9b',
    contentNegative: '#ed4369',
  },
  barStyle: 'dark-content',
}