export default {
  colors: {
    background: '#000',
    buttonPrimaryFill: '#fff',
    buttonPrimaryText: '#1d1f1f',
    buttonPrimarySpinnerFill: '#1d1f1f',
    buttonBorderedText: '#fff',
    buttonBorderedBorder: '#fff',
    buttonBorderedSpinnerFill: '#fff',
    buttonMinimalText: '#fff',
    buttonMinimalSpinnerFill: '#fff',
    headerNavigationFill: '#000',
    listSectionHeaderFill: '#000',
    snackbarFill: '#fff',
    snackbarText: '#1d1f1f',
    iconFill: '#fff',
    contentPrimary: '#fff',
    contentSecondary: '#9c9e9e',
    contentTertiary: '#4f5152',
    contentPositive: '#47fb9b',
    contentNegative: '#ed4369',
  },
  barStyle: 'light-content',
}